## Need to import the Morse class

In [4]:
from src.morse import Morse
data = Morse()

file = "../../Data/test_objects/cube_large_r0.30_n4_v256.volume.ply"
#file = "../../Data/vase_reduced_cleaned.ply"
#file = "../../Data/artefact_31_test/curvature/31_r1.00_n4_v256.volume.ply"
#file = "../../Data/graz/steinbruchwand_ttvc_gmo_2022-11-05_0934/Steinbruchwand_TTVC_GMO_cut_150x200_r15.00_n4_v256.volume.ply"
data.load_mesh_ply(file, quality_index=3, inverted=True)
data.ProcessLowerStars()
data.ExtractMorseComplex()
data.ReduceMorseComplex(0.01)
#pers = 0.06
#data.ExtractMorseCells(pers)
labelfilename = "../old_MorseTheory/Data/results/test_new_mscomplex_visualization_001_false"
data.plot_MorseComplex_ply(0.01,labelfilename, detailed=False, separate_points_file=False)

load_mesh_ply took 0.68049 seconds to execute!
ProcessLowerStars took 0.10933 seconds to execute!
ExtractMorseComplex took 0.22246 seconds to execute!
ReduceMorseComplex took 0.08411 seconds to execute!
plot_MorseComplex_ply took 0.14608 seconds to execute!


In [1]:
from src.evaluation_and_conversion import artifact3D_to_label_dict

filename = "../../Data/artifact3D/Qins-31.mat"
scarfilename = "../../Data/artifact3D/ScarsQins-31.mat"
label_dict = artifact3D_to_label_dict(filename, scarfilename)

Flipparameter:  1
Flipvector:  [1, 1, 1]
Trafomat:
 [[-0.03823216  0.99387093 -0.10372502]
 [ 0.95798446  0.00692652 -0.28673647]
 [ 0.28426059  0.11032951  0.95237772]]
Translation:  [-0.39081864 -0.08168858  0.1156127 ]
4  labels
107133 / 146174  points far away nearest neighbor
Process  39040  unvisited points...


In [ ]:
file = "../../Data/artefact_31_test/curvature/31_r1.00_n4_v256.volume.ply"

import cProfile
import pstats

with cProfile.Profile() as pr:
    data.load_mesh_ply(file, quality_index=3, inverted=True)
    
stats = pstats.Stats(pr)
stats.sort_stats(pstats.SortKey.TIME)
stats.print_stats()

In [ ]:
with cProfile.Profile() as pr:
    data.ProcessLowerStars()
    
stats = pstats.Stats(pr)
stats.sort_stats(pstats.SortKey.TIME)
stats.print_stats()

In [ ]:
with cProfile.Profile() as pr:
    data.ExtractMorseComplex()
    
stats = pstats.Stats(pr)
stats.sort_stats(pstats.SortKey.TIME)
stats.print_stats()

In [ ]:
edge_file = "../old_MorseTheory/Data/results/test_0075_005_edges"
data.plot_SalientEdges_ply(edge_file, 0.075,0.05, only_strong=True)

In [ ]:
stat = data.salient_edge_statistics(nb_bins = 300, log=False, save = False, filepath = 'histogram', show = True)

In [ ]:
filename = "../old_MorseTheory/Data/results/test_006_0075_005_05_seg"
data.Segmentation(0.06, 0.075, 0.05, 0.5, minimum_labels=3)
data.plot_Segmentation_label_txt(0.06, 0.075, 0.05, 0.5, filename)

## Dataset info (Optional)
Prints out info like Vertices, Edges and Faces, as well as the Morse function range

In [ ]:
data

In [ ]:
data.MorseComplex

## Perform Morse Complex Calculations
Use the functions **.ProcessLowerStars()** and **.ExtractMorseComplex()**
- **ProcessLowerStars()** calculates the discrete vector field
- **ExtractMorseComplex()** calculates the Morse complex, so finds the neighborhood relations between critical simplices by finding separatrices from maxima to saddles and from saddles to minima

In [ ]:
#data.calculate_BettiNumbers()

In [ ]:
#data.plot_PersistenceDiagram(save = False, filepath = '../../Data/test_plotting_functions/persistenceDiagram_original')

In [ ]:
#data.calculate_BettiNumbers(0.04)

In [ ]:
#data.plot_PersistenceDiagram(0.04,save = False, filepath = '../../Data/test_plotting_functions/persistenceDiagram_0_04P')

In [ ]:
#stats = data.funval_statistics(nb_bins=200, log=True)

In [ ]:
#print("Stats all fun vals:")
#print(stats['mean'])
#print(stats['std'])

In [ ]:
#stats2 = data.critical_funval_statistics(0,nb_bins=200)

In [ ]:
#print("Stats V:")
#print(stats2['V']['mean'])
#print(stats2['V']['std'])
#print("Stats E:")
#print(stats2['E']['mean'])
#print(stats2['E']['std'])
#print("Stats F:")
#print(stats2['F']['mean'])
#print(stats2['F']['std'])

In [ ]:
#stats3 = data.critical_funval_statistics(0.04,nb_bins=200)

In [ ]:
#print("Stats V:")
#print(stats3['V']['mean'])
#print(stats3['V']['std'])
#print("Stats E:")
#print(stats3['E']['mean'])
#print(stats3['E']['std'])
#print("Stats F:")
#print(stats3['F']['mean'])
#print(stats3['F']['std'])

In [ ]:
#import matplotlib.pyplot as plt
#funvals = []
#for e in stats2['V']['fun_vals']:
#    funvals.append(e)
#for e in stats2['E']['fun_vals']:
#    funvals.append(e)
#for e in stats2['F']['fun_vals']:
#    funvals.append(e)
    
#plt.hist(funvals, bins=200)
#plt.xlabel("Function Value")
#plt.ylabel("Counts")
#plt.title("Combined Histogram")
#plt.show()

In [ ]:
#funvals = []
#for e in stats3['V']['fun_vals']:
#    funvals.append(e)
#for e in stats3['E']['fun_vals']:
#    funvals.append(e)
#for e in stats3['F']['fun_vals']:
#    funvals.append(e)
#    
#plt.hist(funvals, bins=200)
#plt.xlabel("Function Value")
#plt.ylabel("Counts")
#plt.title("Combined Histogram")
#plt.show()

In [ ]:
#data.plot_SalientEdges_ply("../../Data/test_plotting_functions/plot_saledge", 0.06, 0.05)
#data.plot_MorseCells_ply(0.04, "../../Data/test_plotting_functions/plot_cells")
#data.plot_MorseComplex_ply(0.04, "../../Data/test_plotting_functions/plot_complex")

In [ ]:
#stats = data.salient_edge_statistics()

In [ ]:
#print("Stats sepa persistence:")
#print(stats['mean'])
#print(stats['std'])

## Get Morse Complex info (Optional)
Prints out infos on the original Morse complex like number of critical vertices, crit. edges and crit. faces. Persistence should be 0 on the original complex.

In [ ]:
data.MorseComplex.info()

In [ ]:
#labelfile_name = "../../Data/vase_cells_only_label" # the .txt extension is written automatically
#labelfile_name = "../../Data/31_only_label" # the .txt extension is written automatically
labelfile_name = "../../Data/test_objects/cube_large_0_01"

data.ExtractMorseCells(0.01)
data.plot_MorseCells_label_txt(0.01, labelfile_name)
data.plot_MorseCells_ply(0.01, labelfile_name)
data.plot_MorseComplex_ply(0.01, labelfile_name, path_color=[200,200,200])

## Reduce Morse complex (using Persistence)
Use the function **.ReduceMorseComplex(persistence)**
- **persistence:** The persistence level up to which the Morse complex should be simplified. (neighboring critical simplices will be cancelled, (if topologically possible,) if their Morse function value difference is less than the persistence.

The reduced complex will be stored in a dictionary **data.reducedMorseComplexes[persistence]** which allows to calculate several persistences. Can be accessed using the persistence as key.

In [ ]:
#data.ExtractMorseCells(0.04)
#filename = "../../Data/31_testnew_segmentation_no_persistence"
#seg = data.Segmentation(0, 0.06, 0.05, 0.15, minimum_labels=5)
#data.plot_Segmentation_label_txt(0, 0.06, 0.05, 0.15, filename)

In [ ]:
#print(len(seg.Cells.keys()))

In [ ]:
#labelfile_name = "../../Data/vase_cells_only_label_001" # the .txt extension is written automatically
#labelfile_name = "../../Data/31_only_label_004" # the .txt extension is written automatically

#data.ExtractMorseCells(0.04)
#data.write_MorseCellLabels(0.04, labelfile_name)

## Plot option for Gigamesh (there are several also for writing meshlab overlay files..)
Uses a labels for each Morse cell to write a label file which can be read by Gigamesh for visualization.
Need to Extract Morse cells first with **.ExtractMorseCells(persistence)** and than **.write_MorseCellLabels(persistence, filename)** to write the according label file. 
- **persistence:** The persistence of the Morse complex you want to visualize
- **filename:** filename where the label file should be stored

In [ ]:
#labelfile_name = "abc_labels" # the .txt extension is written automatically

#data.ExtractMorseCells(3)
#data.write_MorseCellLabels(3, labelfile_name)

## Visualize in Gigamesh:
(Maybe the develop version of gigamesh is required, since import labels migth not be in the website version)
1. Load the ply file into Gigamesh
2. Choose Import labels under **File - Import - Import Labels** and load the written output label file
3. Vertex in first column: YES 
4. Select **Labels-Connected Comp.** on the right to see the Morse cells of the Morse complex

In [ ]:
import sys
import numpy as np

a=float(0.275369)
b = np.float16(0.275369)
#b = b.astype(np.int32)

print(type(a))
print(sys.getsizeof(a))


print(type(b))
print(sys.getsizeof(b))
import array
b= [1,2,3,0]
c = np.array([1,2,3,0],dtype=np.int8)
a = array.array('L',[1,2,3,0])
print(sorted(a))
print(sys.getsizeof(a))
print(sys.getsizeof(sorted(a)))
print(sys.getsizeof(b))
print(sys.getsizeof(c))
if 2 in a:
    print("ok")
print(a[0])