In [1]:
from src.Algorithms.load_data.Datastructure import Vertex, Simplex
import numpy as np

In [14]:
a1=Vertex(1,1,1,2,0.2,0)
a2=Vertex(1,0,1,3,0.6,1)
a3=Vertex(1,1,0,4,0.1,2)
vert_dict = {0:a1, 1:a2, 2:a3}

In [15]:
b = Simplex({2,0,1},0)

In [16]:
b.compute_area(vert_dict)

0.5

In [17]:
b.face_gradient(vert_dict)

[-0.   0.1  0.4]


In [38]:
k=[[1,2,3],4]
j=[[2,3,4],6]
i=[[0,4,2],3]
c = [k,j,i]
print(np.diff([d[0] for d in c], axis=0))
print(np.diff([d[1] for d in c], axis=0))

[[ 1  1  1]
 [-2  1 -2]]
[ 2 -3]


In [1]:
filename = "../../Data/artefact_31_test/31_r1.00_n4_v256.volume/31_r1.00_n4_v256.volume_0.13H_0.12L_0.3M.txt"

In [8]:
print(float(filename.split("/")[-1].split("_")[-3][:-1]))
print(float(filename.split("/")[-1].split("_")[-2][:-1]))
print(float(filename.split("/")[-1].split("_")[-1][:-5]))

0.13
0.12
0.3


In [1]:
from src.morse import Morse

d=Morse()
d.load_mesh_new("../../Data/artefact_31_test/curvature/31_r1.00_n4_v256.volume.ply")

get edges:  2.263361052999244
set funvals:  3.6525376480021805
load_mesh_new took 7.59726 seconds to execute!


In [3]:
from src.morse import Morse

d=Morse()
d.load_mesh_new("../../Data/test_objects/cube_8p_bin_equalQ.ply")
for v in d.Vertices.values():
    print("Index ",v.index)
    print("Coord ", v.x,v.y,v.z)
    print("funval ", v.fun_val)
    print(v.average_gradient_on_star(d.Vertices, d.Faces))

load_mesh_new took 0.00110 seconds to execute!
Index  0
Coord  -0.5 -0.5 -0.5
funval  0.300000711920929
average_gradient_star:  [-2.e-07 -1.e-07  1.e-07]
[-2.e-07 -1.e-07  1.e-07]
Index  1
Coord  0.5 -0.5 -0.5
funval  0.300000611920929
average_gradient_star:  [ 0.e+00 -8.e-08  4.e-08]
[ 0.e+00 -8.e-08  4.e-08]
Index  2
Coord  -0.5 0.5 -0.5
funval  0.30000051192092897
average_gradient_star:  [-8.e-08  0.e+00  2.e-08]
[-8.e-08  0.e+00  2.e-08]
Index  3
Coord  0.5 0.5 -0.5
funval  0.30000041192092897
average_gradient_star:  [ 4.0000003e-08 -1.9999998e-08  0.0000000e+00]
[ 4.0000003e-08 -1.9999998e-08  0.0000000e+00]
Index  4
Coord  -0.5 -0.5 0.5
funval  0.30000031192092896
average_gradient_star:  [-4.e-08  2.e-08  0.e+00]
[-4.e-08  2.e-08  0.e+00]
Index  5
Coord  0.5 -0.5 0.5
funval  0.30000021192092896
average_gradient_star:  [ 8.0000007e-08  0.0000000e+00 -2.0000002e-08]
[ 8.0000007e-08  0.0000000e+00 -2.0000002e-08]
Index  6
Coord  -0.5 0.5 0.5
funval  0.30000011192092896
average_gradi

In [3]:
a = [((3, [2, 1, 0]),), ((3, [1, 2, 3]),), ((3, [4, 2, 0]),), ((3, [2, 4, 6]),),
 ((3, [1, 4, 0]),), ((3, [4, 1, 5]),), ((3, [6, 5, 7]),), ((3, [5, 6, 4]),),
 ((3, [3, 6, 7]),), ((3, [6, 3, 2]),), ((3, [5, 3, 7]),), ((3, [3, 5, 1]),)]

In [15]:
import numpy as np
x = map(np.array, a)
print(np.array(a[:])[0])

/tmp/ipykernel_26291/2162324525.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(list(x)[:][:,0])


TypeError: list indices must be integers or slices, not tuple

In [12]:
import numpy as np
import itertools

In [50]:
def faces_to_edges(faces, return_index=False):
    """
    Given a list of faces (n,3), return a list of edges (n*3,2)
    Parameters
    -----------
    faces : (n, 3) int
      Vertex indices representing faces
    Returns
    -----------
    edges : (n*3, 2) int
      Vertex indices representing edges
    """
    faces = np.asanyarray(faces)

    # each face has three edges
    edges = faces[:, [0, 1, 1, 2, 2, 0]].reshape((-1, 2))

    if return_index:
        # edges are in order of faces due to reshape
        face_index = np.tile(np.arange(len(faces)),
                             (3, 1)).T.reshape(-1)
        return edges, face_index
    return edges

In [54]:
faces=[[2, 0,1], 
[1, 2, 3],
[4, 2, 0],
[2, 4, 6],
[1, 4, 0],
[4, 1, 5],
[6, 5, 7],
[5, 6, 4],
[3, 6, 7],
[6, 3, 2],
[5, 3, 7],
[3, 5, 1]]
edges, f_ind = faces_to_edges(faces, return_index=True)

In [55]:
print(len(edges))

36


In [56]:

tupled_lst = map(set, edges)
lst = map(tuple, tupled_lst)
#print(len(set(lst)))
s = set(lst)
print(s)
print(len(s))

{(0, 1), (2, 4), (1, 2), (0, 4), (1, 5), (3, 7), (4, 6), (1, 4), (5, 7), (2, 3), (6, 7), (0, 2), (4, 5), (2, 6), (5, 6), (3, 6), (1, 3), (3, 5)}
18


In [11]:
print(f_ind)

[ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7
  8  8  8  9  9  9 10 10 10 11 11 11]
