In [1]:
from src.Algorithms.load_data.Datastructure import Vertex, Simplex
import numpy as np

In [14]:
a1=Vertex(1,1,1,2,0.2,0)
a2=Vertex(1,0,1,3,0.6,1)
a3=Vertex(1,1,0,4,0.1,2)
vert_dict = {0:a1, 1:a2, 2:a3}

In [15]:
b = Simplex({2,0,1},0)

In [16]:
b.compute_area(vert_dict)

0.5

In [17]:
b.face_gradient(vert_dict)

[-0.   0.1  0.4]


In [38]:
k=[[1,2,3],4]
j=[[2,3,4],6]
i=[[0,4,2],3]
c = [k,j,i]
print(np.diff([d[0] for d in c], axis=0))
print(np.diff([d[1] for d in c], axis=0))

[[ 1  1  1]
 [-2  1 -2]]
[ 2 -3]
